CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
                                                       "MigrationId" character varying(150) NOT NULL,
                                                       "ProductVersion" character varying(32) NOT NULL,
                                                       CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "DimCurrency" (
                               "CurrencyKey" text NOT NULL,
                               "CurrencyLabel" text NOT NULL,
                               "CurrencyName" text NOT NULL,
                               "CurrencyDescription" text NOT NULL,
                               simple_string_nullable text NULL,
                               CONSTRAINT "PK_DimCurrency_CurrencyKey" PRIMARY KEY ("CurrencyKey")
);

CREATE TABLE "DimCustomer" (
                               "CustomerKey" integer GENERATED BY DEFAULT AS IDENTITY,
                               "CustomerLabel" text NOT NULL,
                               "Title" text NULL,
                               "FirstName" text NULL,
                               "MiddleName" text NULL,
                               "LastName" text NULL,
                               "NameStyle" boolean NULL,
                               "BirthDate" timestamp with time zone NULL,
                               "MaritalStatus" text NULL,
                               "Suffix" text NULL,
                               "Gender" text NULL,
                               "EmailAddress" text NULL,
                               "YearlyIncome" numeric NULL,
                               "TotalChildren" smallint NULL,
                               "NumberChildrenAtHome" smallint NULL,
                               "Education" text NULL,
                               "Occupation" text NULL,
                               "HouseOwnerFlag" text NULL,
                               "NumberCarsOwned" smallint NULL,
                               "AddressLine1" text NULL,
                               "AddressLine2" text NULL,
                               "Phone" text NULL,
                               "DateFirstPurchase" timestamp with time zone NULL,
                               "CustomerType" text NULL,
                               "CompanyName" text NULL,
                               "Inn" text NULL,
                               "Fat_string" text NULL,
                               simple_string_nullable text NULL,
                               CONSTRAINT "PK_DimCustomer_CustomerKey" PRIMARY KEY ("CustomerKey")
);

CREATE TABLE "DimDate" (
                           "Datekey" timestamp with time zone NOT NULL,
                           "FullDateLabel" text NOT NULL,
                           "DateDescription" text NOT NULL,
                           "CalendarYear" integer NOT NULL,
                           "CalendarYearLabel" text NOT NULL,
                           "CalendarHalfYear" integer NOT NULL,
                           "CalendarHalfYearLabel" text NOT NULL,
                           "CalendarQuarter" integer NOT NULL,
                           "CalendarQuarterLabel" text NULL,
                           "CalendarMonth" integer NOT NULL,
                           "CalendarMonthLabel" text NOT NULL,
                           "CalendarWeek" integer NOT NULL,
                           "CalendarWeekLabel" text NOT NULL,
                           "CalendarDayOfWeek" integer NOT NULL,
                           "CalendarDayOfWeekLabel" text NOT NULL,
                           "FiscalYear" integer NOT NULL,
                           "FiscalYearLabel" text NOT NULL,
                           "FiscalHalfYear" integer NOT NULL,
                           "FiscalHalfYearLabel" text NOT NULL,
                           "FiscalQuarter" integer NOT NULL,
                           "FiscalQuarterLabel" text NOT NULL,
                           "FiscalMonth" integer NOT NULL,
                           "FiscalMonthLabel" text NOT NULL,
                           "IsWorkDay" text NOT NULL,
                           "IsHoliday" integer NOT NULL,
                           "HolidayName" text NOT NULL,
                           "EuropeSeason" text NULL,
                           "NorthAmericaSeason" text NULL,
                           "AsiaSeason" text NULL,
                           "CalendarYearLabelRu" text NULL,
                           "CalendarMonthLabelRu" text NULL,
                           "CalendarWeekLabelRu" text NULL,
                           "CalendarDayOfWeekLabelRu" text NULL,
                           "FiscalYearLabelRu" text NULL,
                           "FiscalMonthLabelRu" text NULL,
                           "IsWorkDayRu" text NULL,
                           "CalendarMonthNumber" integer NULL,
                           "CalendarDayNumber" integer NULL,
                           "CalendarQuarterNumber" integer NULL,
                           "CalendarWeekNumberOfMonth" integer NULL,
                           "CalendarWeekNumberOfYear" integer NULL,
                           simple_string_nullable text NULL,
                           CONSTRAINT "PK_DimDate_DateKey" PRIMARY KEY ("Datekey")
);

CREATE TABLE "DimProduct" (
                              "ProductKey" integer GENERATED BY DEFAULT AS IDENTITY,
                              "ProductLabel" text NULL,
                              "ProductName" text NULL,
                              "ProductDescription" text NULL,
                              "Manufacturer" text NULL,
                              "BrandName" text NULL,
                              "ClassId" text NULL,
                              "ClassName" text NULL,
                              "StyleId" text NULL,
                              "StyleName" text NULL,
                              "ColorId" text NULL,
                              "ColorName" text NOT NULL,
                              "Size" text NULL,
                              "SizeRange" text NULL,
                              "SizeUnitMeasureId" text NULL,
                              "Weight" double precision NULL,
                              "WeightUnitMeasureId" text NULL,
                              "UnitOfMeasureId" text NULL,
                              "UnitOfMeasureName" text NULL,
                              "StockTypeId" text NULL,
                              "StockTypeName" text NULL,
                              "UnitCost" numeric NULL,
                              "UnitPrice" numeric NULL,
                              "AvailableForSaleDate" timestamp with time zone NULL,
                              "StopSaleDate" timestamp with time zone NULL,
                              "Status" text NULL,
                              "Brandname_id_nullable" integer NULL,
                              "Brandname_id" integer NULL,
                              "Classname_id_nullable" integer NULL,
                              "Classname_id" integer NULL,
                              "Brandname_string_nullable" text NULL,
                              "Classname_string_nullable" text NULL,
                              "Status_bool" boolean NULL,
                              "Status_bool_nullable" boolean NULL,
                              simple_string_nullable text NULL,
                              CONSTRAINT "PK_DimProduct_ProductKey" PRIMARY KEY ("ProductKey")
);

CREATE TABLE "DimPromotion" (
                                "PromotionKey" integer GENERATED BY DEFAULT AS IDENTITY,
                                "PromotionLabel" text NULL,
                                "PromotionName" text NULL,
                                "PromotionDescription" text NULL,
                                "DiscountPercent" double precision NULL,
                                "PromotionType" text NULL,
                                "PromotionCategory" text NULL,
                                "StartDate" timestamp with time zone NOT NULL,
                                "EndDate" timestamp with time zone NULL,
                                "MinQuantity" integer NULL,
                                "MaxQuantity" integer NULL,
                                simple_string_nullable text NULL,
                                CONSTRAINT "PK_DimPromotion_PromotionKey" PRIMARY KEY ("PromotionKey")
);

CREATE TABLE "DimPromotionNullableKey" (
                                           "PromotionKey" integer NULL,
                                           "PromotionLabel" text NULL,
                                           "PromotionName" text NULL,
                                           "PromotionDescription" text NULL,
                                           "DiscountPercent" double precision NULL,
                                           "PromotionType" text NULL,
                                           "PromotionCategory" text NULL,
                                           "StartDate" timestamp with time zone NOT NULL,
                                           "EndDate" timestamp with time zone NULL,
                                           "MinQuantity" integer NULL,
                                           "MaxQuantity" integer NULL,
                                           simple_string_nullable text NULL
);

CREATE TABLE "DimStore" (
                            "StoreKey" integer GENERATED BY DEFAULT AS IDENTITY,
                            "GeographyKey" integer NOT NULL,
                            "StoreManager" integer NULL,
                            "StoreType" text NULL,
                            "StoreName" text NOT NULL,
                            "StoreDescription" text NOT NULL,
                            "Status" text NOT NULL,
                            "OpenDate" timestamp with time zone NOT NULL,
                            "CloseDate" timestamp with time zone NULL,
                            "EntityKey" integer NULL,
                            "ZipCode" text NULL,
                            "ZipCodeExtension" text NULL,
                            "StorePhone" text NULL,
                            "StoreFax" text NULL,
                            "AddressLine1" text NULL,
                            "AddressLine2" text NULL,
                            "CloseReason" text NULL,
                            "EmployeeCount" integer NULL,
                            "SellingAreaSize" double precision NULL,
                            "LastRemodelDate" timestamp with time zone NULL,
                            simple_string_nullable text NULL,
                            CONSTRAINT "PK_DimStore_StoreKey" PRIMARY KEY ("StoreKey")
);

CREATE TABLE "FactOfflineSales" (
                                    "OfflineSalesKey" integer GENERATED BY DEFAULT AS IDENTITY,
                                    "DateKey" timestamp with time zone NOT NULL,
                                    "StoreKey" integer NOT NULL,
                                    "ProductKey" integer NOT NULL,
                                    "PromotionKey" integer NOT NULL,
                                    "PromotionKeyNullable" integer NULL,
                                    "CurrencyKey" text NOT NULL,
                                    "CustomerKey" integer NOT NULL,
                                    "SalesOrderNumber" text NOT NULL,
                                    "SalesOrderLineNumber" integer NULL,
                                    "SalesQuantity" integer NOT NULL,
                                    "SalesAmount" numeric NOT NULL,
                                    "ReturnQuantity" integer NOT NULL,
                                    "ReturnAmount" numeric NULL,
                                    "DiscountQuantity" integer NULL,
                                    "DiscountAmount" numeric NULL,
                                    "TotalCost" numeric NOT NULL,
                                    "UnitCost" numeric NULL,
                                    "UnitPrice" numeric NULL,
                                    simple_string_nullable text NULL,
                                    CONSTRAINT "PK_FactOfflineSales_SalesKey" PRIMARY KEY ("OfflineSalesKey"),
                                    CONSTRAINT "FK_FactOfflineSales_DimCurrency" FOREIGN KEY ("CurrencyKey") REFERENCES "DimCurrency" ("CurrencyKey"),
                                    CONSTRAINT "FK_FactOfflineSales_DimCustomer" FOREIGN KEY ("CustomerKey") REFERENCES "DimCustomer" ("CustomerKey"),
                                    CONSTRAINT "FK_FactOfflineSales_DimDate" FOREIGN KEY ("DateKey") REFERENCES "DimDate" ("Datekey"),
                                    CONSTRAINT "FK_FactOfflineSales_DimProduct" FOREIGN KEY ("ProductKey") REFERENCES "DimProduct" ("ProductKey"),
                                    CONSTRAINT "FK_FactOfflineSales_DimPromotion" FOREIGN KEY ("PromotionKey") REFERENCES "DimPromotion" ("PromotionKey"),
                                    CONSTRAINT "FK_FactOfflineSales_DimStore" FOREIGN KEY ("StoreKey") REFERENCES "DimStore" ("StoreKey")
);

CREATE TABLE "FactOnlineSales" (
                                   "OnlineSalesKey" integer GENERATED BY DEFAULT AS IDENTITY,
                                   "DateKey" timestamp with time zone NOT NULL,
                                   "StoreKey" integer NOT NULL,
                                   "ProductKey" integer NOT NULL,
                                   "PromotionKey" integer NOT NULL,
                                   "PromotionKeyNullable" integer NULL,
                                   "CurrencyKey" text NOT NULL,
                                   "CustomerKey" integer NOT NULL,
                                   "SalesOrderNumber" text NOT NULL,
                                   "SalesOrderLineNumber" integer NULL,
                                   "SalesQuantity" integer NOT NULL,
                                   "SalesAmount" numeric NOT NULL,
                                   "ReturnQuantity" integer NOT NULL,
                                   "ReturnAmount" numeric NULL,
                                   "DiscountQuantity" integer NULL,
                                   "DiscountAmount" numeric NULL,
                                   "TotalCost" numeric NOT NULL,
                                   "UnitCost" numeric NULL,
                                   "UnitPrice" numeric NULL,
                                   simple_string_nullable text NULL,
                                   CONSTRAINT "PK_FactOnlineSales_SalesKey" PRIMARY KEY ("OnlineSalesKey"),
                                   CONSTRAINT "FK_FactOnlineSales_DimCurrency" FOREIGN KEY ("CurrencyKey") REFERENCES "DimCurrency" ("CurrencyKey"),
                                   CONSTRAINT "FK_FactOnlineSales_DimCustomer" FOREIGN KEY ("CustomerKey") REFERENCES "DimCustomer" ("CustomerKey"),
                                   CONSTRAINT "FK_FactOnlineSales_DimDate" FOREIGN KEY ("DateKey") REFERENCES "DimDate" ("Datekey"),
                                   CONSTRAINT "FK_FactOnlineSales_DimProduct" FOREIGN KEY ("ProductKey") REFERENCES "DimProduct" ("ProductKey"),
                                   CONSTRAINT "FK_FactOnlineSales_DimPromotion" FOREIGN KEY ("PromotionKey") REFERENCES "DimPromotion" ("PromotionKey"),
                                   CONSTRAINT "FK_FactOnlineSales_DimStore" FOREIGN KEY ("StoreKey") REFERENCES "DimStore" ("StoreKey")
);

CREATE UNIQUE INDEX "AK_DimCurrency_CurrencyLabel" ON "DimCurrency" ("CurrencyLabel");

CREATE UNIQUE INDEX "IX_DimCustomer_CustomerLabel" ON "DimCustomer" ("CustomerLabel");

CREATE UNIQUE INDEX "AK_DimPromotion_PromotionLabel" ON "DimPromotion" ("PromotionLabel");

CREATE INDEX "IX_FactOfflineSales_CurrencyKey" ON "FactOfflineSales" ("CurrencyKey");

CREATE INDEX "IX_FactOfflineSales_CustomerKey" ON "FactOfflineSales" ("CustomerKey");

CREATE INDEX "IX_FactOfflineSales_DateKey" ON "FactOfflineSales" ("DateKey");

CREATE INDEX "IX_FactOfflineSales_ProductKey" ON "FactOfflineSales" ("ProductKey");

CREATE INDEX "IX_FactOfflineSales_PromotionKey" ON "FactOfflineSales" ("PromotionKey");

CREATE INDEX "IX_FactOfflineSales_StoreKey" ON "FactOfflineSales" ("StoreKey");

CREATE INDEX "IX_FactOnlineSales_CurrencyKey" ON "FactOnlineSales" ("CurrencyKey");

CREATE INDEX "IX_FactOnlineSales_CustomerKey" ON "FactOnlineSales" ("CustomerKey");

CREATE INDEX "IX_FactOnlineSales_DateKey" ON "FactOnlineSales" ("DateKey");

CREATE INDEX "IX_FactOnlineSales_ProductKey" ON "FactOnlineSales" ("ProductKey");

CREATE INDEX "IX_FactOnlineSales_PromotionKey" ON "FactOnlineSales" ("PromotionKey");

CREATE INDEX "IX_FactOnlineSales_StoreKey" ON "FactOnlineSales" ("StoreKey");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231021164956_MyMigration', '7.0.12');

COMMIT;

